# Generated by Django 2.2 on 2019-04-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='agree',
            field=models.BooleanField(default=True),
        ),
    ]
