# Generated by Django 2.2 on 2019-04-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20190422_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company_size',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='state',
        ),
    ]
