# Generated by Django 2.2 on 2019-04-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20190423_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_no',
            field=models.CharField(max_length=10),
        ),
    ]
