# Generated by Django 2.2 on 2019-04-26 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20190425_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='subject',
            field=models.CharField(choices=[('', 'Choose a Subject'), ('Suggestions', 'suggestions'), ('Compliment', 'Compliment')], max_length=200),
        ),
    ]
